### ISSUE TITLE
Select option label not working in Firefox

### ISSUE THREAD

**Issue by jerone** [praeclarum/Ooui#103]
The `label` attribute for the `select` `option` is not working in Firefox.

See https://www.w3schools.com/tags/att_option_label.asp and the remarks here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#Browser_compatibility

### Steps to reproduce

1. Open example in Firefox http://ooui.mecha.parts/Samples/Run/Drawing
2. See that the dropdown contains two empty options.

**Comment by praeclarum** [comment]
Firefox!!! Thanks. This is surprising since I tend to use MDN docs for HTML reference haha.

Actually, ooui.mecha.parts is a bit old. Perhaps it just needs updating. Thanks!

**Comment by praeclarum** [comment]
I updated the website and the bug is still there. Gosh I feel like I fixed this one already. Thanks for the report!

**Comment by jerone** [comment]
Because it creates _invalid_ HTML:

```html
<option id="⦙3825" label="Boxes" value="box" />
```

Valid:
```html
<option id="⦙3825" label="Boxes" value="box">Boxes</option>
```

----

_BTW: what's with the weird `id`?_

**Comment by praeclarum** [comment]
The HTML is valid and works according to the docs:

<img width="716" alt="screenshot 2018-03-17 10 07 32" src="https://user-images.githubusercontent.com/323548/37558046-23005d64-29cb-11e8-9133-5f0184da94be.png">

(from https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option)

It uses label and value attributes.  But I guess I can put in text content too...

The ID has a sentinel character in the beginning to aide in deserializing command packets. I picked a unicode character that fits well into UTF-8, but has almost no usage on the internet.

**Comment by jerone** [comment]
The `option` element is not a self-closing tag; _"Tag omission | The start tag is mandatory. The end tag is optional if this element is immediately followed by another `<option>` element or an `<optgroup>`, or if the parent element has no more content."_ (See header).

And because of a bug; _"Firefox doesn't display the value of the label attribute as option text if element's content is empty. See bug 40545."_ (See implementation notes in the Browser compatibility tablet).

**Comment by praeclarum** [comment]
@jerone Thanks for the reference! Sounds like I better change things!

**Comment by praeclarum** [comment]
I **love** that that bug is 18 years old!

**Comment by krystian3w** [comment]
Fixed in Firefox 77.
