### ISSUE TITLE
GetUserStoreForApplication is not implmented - breaks UrlImageSource

### ISSUE THREAD

**Issue by michael-watson** [praeclarum/Ooui#104]
Love the work so I'm trying to take my wedding website and port it over to this project for fun. I got some things figured out, but when I load an image from blob storage, Chrome gives me the crash shown below. 

```csharp
//Code for loading up image
var mainImage = new Image
{
    Source = "https://{MyBlobContainer}.blob.core.windows.net/images-public/front.jpeg"
};
```
<img width="1076" alt="error in chrome" src="https://user-images.githubusercontent.com/8645958/37558512-73eb94d0-29d2-11e8-8465-81a3af4ed8fa.png">

[This](https://github.com/xamarin/Xamarin.Forms/blob/ff40c5b4e1e6ef62ef1972db3dd3a67617095eb0/Xamarin.Forms.Core/UriImageSource.cs#L19) is where `Forms` references it and utilizes it for caching purposes. 

@praeclarum Do you have any plans here yet for what to plug in for the `IIsolatedStorageFile` implementation?

**Comment by michael-watson** [comment]
@praeclarum It is for local caching available from the [`UriImageSource.CachingEnabled`](https://developer.xamarin.com/api/property/Xamarin.Forms.UriImageSource.CachingEnabled/)(enabled by default) and you can view the source [here](https://github.com/xamarin/Xamarin.Forms/blob/ff40c5b4e1e6ef62ef1972db3dd3a67617095eb0/Xamarin.Forms.Core/UriImageSource.cs#L48)

Maybe it's more that we need to expose the browser cache and utilize the [HTTP Caching](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching) capabilities of the browser for that image url. 

I won't have time to dig into this for now, but maybe in a week or so I'll look into this deeper. 

For anyone else hitting this issue, you will need to manually load the image into your source. You can do this by utilizing `HttpClient.GetStreamAsync()` for the endpoint of your url, then utilize that `Stream` as the source for your image. This will bypass the `UriImageSource` and caching capabilities. If you wanted to cache that `Stream`, you will have to write that logic for now.

**Comment by michael-watson** [comment]
Scratch that, I am able to have this code working for the iOS/Android projects, but it doesn't work in the website. I'm not getting any errors in the developer tools so I'm not sure what is going on there. I'll report back if I figure out anything else in this direction.

**Comment by praeclarum** [comment]
@michael-watson I'm going to start packaging debug versions of the runtime when you make a Debug build. That will show your Debug.WriteLines. I've resisted because Chrome has a bug that makes loading super slow.

I still need to investigate images - they were purposefully off my radar in the beginning as it's a little tricky how to get them into the DOM. But people obviously want them now :-)
