### ISSUE TITLE
Ooui.Forms:  LoadApplication?

### ISSUE THREAD

**Issue by BradChase2011** [praeclarum/Ooui#106]
I wanted to start off by saying, awesome job on all this!  I am currently trying to get it running with our application to see what needs done at this point.  We have the login screen sorta coming up, everything is laid out vertical regardless of overlapping, BUT its a start and amazing to see this showing up.  So thanks again for that!

OK, on to the problem is how do we LoadApplication?  iOS, WPF, UWP, macOS, Droid all have a LoadApplication but since it inherits from Element and not Page we cant do your style of loading with the Publish, Present... This means that our Application never really loads and all of our Resources are null.

Any ideas on what should be the next step here?  Is Application looking to be implemented at some point?

Thanks much!

**Comment by jamesmontemagno** [comment]
Se the docs here: https://github.com/praeclarum/Ooui/wiki/Xamarin.Forms-on-the-Web

You don't load the application at all. Think of classic ASP.NET + MVC and each View is a Xamarin.Forms view.

**Comment by jamesmontemagno** [comment]
Also see: https://montemagno.com/building-a-xaml-xamarin-forms-asp-net-website/

**Comment by BradChase2011** [comment]
I went ahead and switched over to that route but I failed to get how that sets an Application.  So for instance on the C# client side we will use alot of ((IApplication)System.Windows.Application.Current) where IApplication is an interface for our main App...  Unfortunately the Application type is of Xamarin.Forms.PageExtensions.DefaultApplication.  Further along, how should resources be loaded?  For instance, Xamarin.Forms.Application.Current.Resources is always null, strangely because it should never return null.

Now I know for sure I dont quite understand the purpose of this or what I should be expecting.  What I am trying to get it to do is run our existing code in a browser.  Am I far off on that?  Or what piece am I missing?  Thanks much for helping out here James.

**Comment by michael-watson** [comment]
Unfortunately @BradChase2011 , this project is in a state where you will most likely not be able to just take your existing code and run it. There is still work to be done to make that happen, but progress is going well. 

The reason for the `Application` having a lot not there is because it just hasn't been implemented yet. For example, if you use `NavigationPage`, you can't use any navigation because it just hasn't been implemented yet, see [here](https://github.com/praeclarum/Ooui/blob/master/Ooui.Forms/Platform.cs#L200).

I'm currently trying to use this project for something completely new and I ran into problems with images. I've started to fork the repo and figure things out myself to help contribute. I would strongly recommend this approach if you would like this project to move faster.

**Comment by BradChase2011** [comment]
Ahh yea I fully grasp that part :).  The idea is to see how far along it is and like you, what might be needed.  Speaking of images, I just got our svgs loading today and images showing up.  They show up, but load weirdly, sometimes with tiling, sometimes with vertical orientations.  But its fun to see regardless!

**Comment by michael-watson** [comment]
Can you share what you did? I just was working on embedded images, but it looks like the resources aren't being copied over from the chrome developer tools.

**Comment by BradChase2011** [comment]
Well as strange as it happens, Frank had an SVG library he made quite a bit back and I had forked it a long time ago and have been keeping it up for our stuff.  It wont do crazy or complicated SVGs, but it will put use just about every google material design icon and our custom SVGs for logos and such.  Then I use a custom renderer to render them into a MemoryStream and set the Image.Source with ImageSource.FromStream(() => new MemoryStream(data))...  The SVGs are stored as embedded resources...

**Comment by michael-watson** [comment]
Very interesting, I'm just getting 404 file not found after it tries loading the resource for a few seconds. If I change the resource name to something I know is wrong, it fails immediately.

![image](https://user-images.githubusercontent.com/8645958/37570827-f8de6a2a-2ab1-11e8-8eeb-cf641dbdf03e.png)

I'll have to keep playing around to figure out what's going on. Thanks for sharing!

**Comment by BradChase2011** [comment]
Sure, Ill keep track of the other post and try to see whats going on there.  I just put them in the project and then knock them with Embedded resource and set to "Do not copy"  If I set it to copy then it will fail as well.  Try making sure you can get your assembly from the name and then check the resources in the assembly to verify they are actually in there.

**Comment by BradChase2011** [comment]
Hmm I have it working under both.  Try to do a from stream, so get the resource as bytes and do from stream.. see if that works

**Comment by jamesmontemagno** [comment]
For images they need to be an embedded resource.

I use a converter for the xaml:

```
namespace Soundbite.Converters
{
    public class ImageSourceConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var defaultId = "Soundbite.Images.soundbiteartwork_small.jpg";
            var id = parameter as string;
            if (!string.IsNullOrWhiteSpace(id))
            {
                try
                {
                    return ImageSource.FromResource($"Soundbite.Images.{id}", System.Reflection.Assembly.GetExecutingAssembly());
                }
                catch (Exception)
                {
                    Console.WriteLine($"Unable to load {id} artwork");
                }
            }


            return ImageSource.FromResource(defaultId, System.Reflection.Assembly.GetExecutingAssembly());
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}
```

**Comment by praeclarum** [comment]
In 0.9 you will be able to call:

```csharp
Forms.LoadApplication(new MyApp());
```

That results in publishing the main page to "/" as WASM expects.

**Comment by BradChase2011** [comment]
Thanks much Frank!  I'll give it a shot here shortly.  When I get some free time I'll start to look into some of the drawing issues were having with our login screen not laying out correctly.
