### ISSUE TITLE
Forms + Wasm. Xaml BindingContext does not work

### ISSUE THREAD

**Issue by MisterJimson** [praeclarum/Ooui#107]
Sample: https://github.com/MisterJimson/WebFormsDemo/tree/binding-test

Sample is a Hello World Ooui.Forms + Ooui.Wasm app that displays 2 messages. One set in xaml directly and one bound to a ViewModel property.

I got the same result on Windows and macOS.

**Versions**
Ooui.Forms Version="0.8.186" 
Ooui.Wasm Version="0.8.186"
Xamarin.Forms Version="2.5.0.280555"
.NET Command Line Tools (2.1.4)
Microsoft .NET Core Shared Framework Host Version  : 2.0.5

**Expected**
Both messages display their content.

**Actual**
The string directly from xaml displays correctly.
The string set by BindingContext does not display.

**Comment by bitdisaster** [comment]
I believe that is the same thing I encounter https://github.com/praeclarum/Ooui/issues/113
