### ISSUE TITLE
How to send data back to the server?

### ISSUE THREAD

**Issue by jptarqu** [praeclarum/Ooui#110]
Hi, Is there a sample on how to send data to the server (like a HTTP POST) when using Ooui.WASM?

Thank you for your awesome work!

**Comment by praeclarum** [comment]
Thanks! HttpClient will be the recommended way to do this (and libraries that use HttpClient). Unfortunately, I don't have any samples or tests for it right now (was focused on client side) and am not even sure if it works. Need to test :-)
