### ISSUE TITLE
Input.Value returning empty string

### ISSUE THREAD

**Issue by arivoir** [praeclarum/Ooui#111]
I'm trying to get the value of a Input of type "text" from the KeyUp event handler, but it returns an empty string (or null, I'm not sure)

`_input = new Input(InputType.Text);
_input.KeyUp += OnKeyUp;`

`private static void OnKeyUp(object sender, TargetEventArgs e)
{
    var theValue = _input.Value;//This is not working, strangely _input.Value returns null.
}
`

**Comment by praeclarum** [comment]
Ah yes, a few events are marked as "value changes as a result" and unfortunately I didn't mark the key events with this. Should be easy to fix.

https://github.com/praeclarum/Ooui/blob/0a8898e1b2d88215ff83960ccd539c116cda796d/Ooui/Client.js#L255
