### ISSUE TITLE
Binding does not work

### ISSUE THREAD

**Issue by bitdisaster** [praeclarum/Ooui#113]
I tried to get a simple example running.  I installed the latest nuget versions. However, binding a label to a property does not work. 

 ```
  <ContentPage.BindingContext>
        <vm:MainViewModel />
    </ContentPage.BindingContext>
```

    <Label Text="{Binding Path=Test, Mode=OneWay}"
                VerticalOptions="CenterAndExpand" 
                HorizontalOptions="CenterAndExpand" />

```
public class MainViewModel : ViewModelBase
    {
        private string _test = "Hello Ooui";
        public string Test
        {
            get { return _test; }
            set { Set(ref _test, value); }
        }
    }
```

As you can see nothing special.  If I remove the Path and just call Binding I can see that the BindingContext has an instance of MainViewModel.

**Comment by bitdisaster** [comment]
I found a workaround. The Binding works if the ViewModel gets touched somehow in code behind. I can put the following code in a click handler and it works. 
 
```
  private  void Track_Clicked(object sender, EventArgs e)
        {
           Console.WriteLine("context " + (BindingContext as MainViewModel)?.Test);           
        }
```

The kicker is I don't have to click the button. So the code never runs. Still it makes a difference. The problem is that I have to do this for each property. So if I want to add another property lets say Test2 then I need to add

`Console.WriteLine("context " + (BindingContext as MainViewModel)?.Test2); `

To me it looks like a property does not get compiled to the "wasm world" (my uneducated naming here) unless it is referenced in C# code. Optimization???

**Comment by solatticus** [comment]
Maybe try the [Preserve] attribute

**Comment by bitdisaster** [comment]
Nope, [Preserve] doesn't make a difference.

**Comment by jamesmontemagno** [comment]
I set the view model in the code behind

**Comment by bitdisaster** [comment]
Hmm. Doesn't make a difference for me. Still have to touch the properties.

**Comment by bitdisaster** [comment]
Wanted to see what properties are there when I don't reference them.

```
            Type t = BindingContext.GetType();
            var props = t.GetProperties();
            foreach (PropertyInfo prp in props)
            {
                Console.WriteLine($"Prop: {prp}");
            }

```
Unfortunately that  errors at compile time. 

`nuget\packages\ooui.wasm\0.8.186\build\netstandard2.0\Ooui.Wasm.targets(17,3): error : Error processing method: 'System.Void CalorieCounter.View.MainView::.ctor()' in assembly: 'CalorieCounter.dll'`

**Comment by jamesmontemagno** [comment]
Probably seams like a bug or issue with the wasm part... any reason you are using the wasm part and not just the standard ooui and forms as all that stuff works fine.

**Comment by bitdisaster** [comment]
But then I have to do <shenanigan>server web stuff</shenanigan> :)
But for real. I 'm excited about the wasm runtime and wanted to see if I can build an App with this. It feels like Silverlight (sorry that I used the S word) reborn.

**Comment by Mike-EEE** [comment]
> sorry that I used the S word

SECURITY, REMOVE THIS MAN AND REVOKE HIS BROGRAMMER CARD!!! 🤣

**Comment by bitdisaster** [comment]
I listen to all of mergeconflict :)

**Comment by rockfordlhotka** [comment]
I am seeing where binding doesn't work either. My simple test _was_ working, then stopped for no apparent reason, and now I can't get it working again. So there's something odd going on for sure!

**Comment by praeclarum** [comment]
@rockfordlhotka make sure to clear your browser cache from time to time. Chrome for instance is very aggressive and you might get out of sync assemblies when doing development.

So far it sounds like the linker is to blame. Investigating...

**Comment by bitdisaster** [comment]
Thanks for fixing.Looking forward to 0.9
