### ISSUE TITLE
Canvas + WASM Issues

### ISSUE THREAD

**Issue by pmoorelegistek** [praeclarum/Ooui#115]
I'm having some trouble working with a Canvas DrawingContext and Ooui-Wasm.

Here's the code:

```
using System;
using Ooui;

namespace MyApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create the UI            
            var canvas = new Canvas
            {
                Width = 320,
                Height = 240
            };

            var context = canvas.GetContext2D();
            canvas.Style.BackgroundColor = "#808080";
            canvas.Style.Cursor = "pointer";

            canvas.Click += (s, e) => {
                var radius = 10;
                context.BeginPath();
                context.Rect(e.OffsetX - radius, e.OffsetY - radius, 2 * radius, 2 * radius);
                context.Fill();
            };

            canvas.Style.Cursor = "pointer";
            canvas.Style.BorderColor = "#CCC";
            canvas.Style.BorderStyle = "solid";
            canvas.Style.BorderWidth = "1px";

            Div d = new Div();            
            d.AppendChild(canvas);

            // Publish a root element to be displayed
            UI.Publish("/", d);
        }
    }
}
```

Was basically trying to recreate the Canvas example but through WASM/client-side .

Two issues arise:
The actual width and height of the Canvas are huge - it's rendering as 320320 x 240240 instead of 320x240.

Then on the Click event, nothing is being drawn. However the Browser Console errors are:

Unknown node id {m: "call", id: "⦙1", k: "beginPath", v: Array(0)}		ooui.js:224
Unknown node id {m: "call", id: "⦙1", k: "rect", v: Array(4)}			ooui.js:224
Unknown node id {m: "call", id: "⦙1", k: "fill", v: Array(0)}			ooui.js:224

Any ideas? Thanks!

**Comment by praeclarum** [comment]
Your code certainly looks right. I have a non-wasm Canvas example: 

http://ooui.mecha.parts/Samples/Run/Drawing

and that seems to behave. I'll have to debug this puppy - the dimensions bug is especially nutty to me.
