### ISSUE TITLE
Page OnAppearing doesn't get raised

### ISSUE THREAD

**Issue by rockfordlhotka** [praeclarum/Ooui#116]
I often put code in the `OnAppearing` handling behind a page to do various initialization activities that can't occur in the constructor. Much like the old Loading or OnLoading events from all previous UI technologies.

The `OnAppearing` event doesn't seem to ever be raised by Ooui in wasm. From what I can find there is _no_ event raised when an XF page appears in the browser.

**Comment by praeclarum** [comment]
Ahh, yes this is important. I think I just forgot to implement it. I'll try to get it into 0.9.

https://github.com/praeclarum/Ooui/blob/master/Documentation/OouiFormsStatus.md#contentpage
