### ISSUE TITLE
Difficult to track down referencing errors.

### ISSUE THREAD

**Issue by yowl** [praeclarum/Ooui#118]
Can we get more feedback for linking errors such as 
`C:\Users\zzzzz\.nuget\packages\ooui.wasm\0.9.206\build\netstandard2.0\Ooui.Wasm.targets(17,3): error : Error while processing references of 'MyFormsApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

**Comment by praeclarum** [comment]
Absolutely.

Can you help me with a repro? Is there a nuget I can reference or something to produce the error?

**Comment by yowl** [comment]
I tried to reference SkiaSharp via nuget and create a SKPath in your sample
`            var x = new SKPath();`
Fighting with the repro/nuget/VS2017 preview...

**Comment by yowl** [comment]
Actually maybe just best to close this until I get a better exmaple. I wanted to bring in SkiaSharp as it was a dependency of Telerik's Xamarin controls, but on investigation I see this is a 2d drawing library which is clearly not going to work without out a backed for the web.

**Comment by praeclarum** [comment]
OK. Yeah I want to support SKia but might have to create a new package to do it.

I'm going to keep this open for now since I want better errors too.

**Comment by praeclarum** [comment]
The errors have been improved to display exactly what it can't find.
