### ISSUE TITLE
Issue with packages and/or .Net Core Preview SDK

### ISSUE THREAD

**Issue by MarkStega** [praeclarum/Ooui#119]
I am trying to follow the Wiki page 'Xamarin.Forms with WebAssembly'

Reading the entire article, I started with getting dotnet-serve; Instructions on the repository page say that '2.1.300-preview1 .NET Core SDK' is required. So I installed the 2.1.300 preview, the dotnet-serve current version, and then proceeded to follow the steps of the original page.

On attempting to add the first package I receive the following error:

```
C:\Solutions\OHI\ooui>dotnet add package Ooui.Wasm
  Writing C:\Users\ms\AppData\Local\Temp\tmpF2D9.tmp
info : Adding PackageReference for package 'Ooui.Wasm' into project 'C:\Solutions\OHI\ooui\ooui.csproj'.
log  : Restoring packages for C:\Solutions\OHI\ooui\ooui.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/ooui.wasm/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/ooui.wasm/index.json 313ms
error: Cycle detected.
error:   ooui -> Ooui.Wasm 0.9.206 -> Ooui (>= 0.9.206).
info : Package 'Ooui.Wasm' is compatible with all the specified frameworks in project 'C:\Solutions\OHI\ooui\ooui.csproj'.
info : PackageReference for package 'Ooui.Wasm' version '0.9.206' added to file 'C:\Solutions\OHI\ooui\ooui.csproj'.

C:\Solutions\OHI\ooui>
```
The same error occurs when trying to add Ooui.Forms

Is this an issue with the Nuget packages or the 2.1.300 SDK?

[Edit - Fixed a typo in a version number]

**Comment by MarkStega** [comment]
I backed the SDK version down to 2.1.103 (the current version that support .Net 2.0.6) and I see the same error reported

**Comment by praeclarum** [comment]
Don’t name your project Ooui by itself. It’s a bug in the new project system and nuget. It thinks your project is the main dll.

**Comment by MarkStega** [comment]
Thanks, that certainly wasn't clear from the error message!
