### ISSUE TITLE
Redirecting browser from server side

### ISSUE THREAD

**Issue by mcintyre321** [praeclarum/Ooui#122]
Is there a way to redirect the users browser (i.e. change window.location) to another url when using server side Ooui? thanks!

**Comment by praeclarum** [comment]
I've been working on exposing the Window object but haven't been happy with my attempts.

I will work on it for v0.10.

For now, you can do something really hacky:

```csharp
var div = new Div();
div.Send (new Message {
                MessageType = MessageType.Set,
                TargetId = "window",
                Key = "location",
                Value = "http://yahoo.com",
            });
```

**Comment by praeclarum** [comment]
I'll track improving this in #124
