### ISSUE TITLE
DLLimport a webassembly module

### ISSUE THREAD

**Issue by roozbehid-ic** [praeclarum/Ooui#128]
Is there a way to do this for a code running in browser? Meaning to dynamically load WebAssembly module.

    [DllImport("mymodule.bc")]

didn't work for me. I think it assumes .Net IL code.
The reason I want this is I have a dynamic library in C++ which I want to call it from C#.

**Comment by ericsink** [comment]
DllImport is for native code, usually written in C or something equivalent.

FWIW, see the following repo for some interesting stuff in the general area around your question:

https://github.com/RyanLamansky/dotnet-webassembly

**Comment by roozbehid-ic** [comment]
So what does native mean in context of WebAssembly. I want to run the generated code in browser, so mono.wasm and mono.js run my managed .Dll. So now what does DllImport mean?

**Comment by ericsink** [comment]
Hmmm.  Never mind my previous comment.

I suppose the question is: When running IL code that has been compiled to wasm, is there a way to call other wasm code? And if so, it DllImport the mechanism to do that?

And I don't know the answer to that. But it's interesting.

**Comment by yowl** [comment]
That's not going to work right now as I understand things.  Pinvoke is not implemented in mono-wasm at least partly because dynamic linking in wasm is hard.  Maybe if you statically linked it all into one module, or the corert/wasm effort which has a different strategy to linking I think.

**Comment by praeclarum** [comment]
PInvokes can work, but you will need to recompile the wasm file and statically link the library into it. You would then use `[DllImport("__Internal")]`.

While this may be something to support in the future, I don't plan on supporting any native code at the moment. Sorry!

**Comment by praeclarum** [comment]
I should note that when we get this working with AOT mode, linking libraries in should be easier.
