### ISSUE TITLE
The sample not working in Edge

### ISSUE THREAD

**Issue by kant2002** [praeclarum/Ooui#144]
Open https://s3.amazonaws.com/praeclarum.org/wasm/index.html in Edge
There error `SCRIPT5022: ValidationError mono.js (1,11239)` in the console. Looks like it is somewhere in the UTF8 decoder, but I'm not sure. Either in the `function lengthBytesUTF8(str) {` function, or in this line `var UTF16Decoder = typeof TextDecoder !== "undefined" ? new TextDecoder("utf-16le") : undefined;`. At least this is where debugger pointed

**Comment by praeclarum** [comment]
Ouch. I was testing in Edge at first so I wonder what changed. Thanks for the details.

**Comment by MarkStega** [comment]
Whatever it was it is working in Edge for me as of a couple of minutes ago.

**Comment by praeclarum** [comment]
Well that's good news? :-/ Please re-open if it happens again.
