### ISSUE TITLE
Endless loading when serving build oui wasm project as static files in asp net core

### ISSUE THREAD

**Issue by FrancoisM** [praeclarum/Ooui#148]
I followed[ Frank's tutorial](https://github.com/praeclarum/Ooui/wiki/Xamarin.Forms-with-Web-Assembly) to create my first Ooui wasm project. I can serve it well locally.
Then I copied the content of the dist folder into the wwwroot of an asp net core project. I added             `app.UseStaticFiles();` (I didn't serve any static contents in that project until now as this is a web api actually). Then I navigated to index.html and I have the loading activity indicator but it is endless.

**Comment by zbigniew-gajewski** [comment]
You need to add custom content types (".wasm", ".dll") in Startup (Configure method snippet attached). Working example [here](https://github.com/zbigniew-gajewski/ooui-wasm-aspnet-core-xaml).

```
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
   // Set up custom content types - associating file extension to MIME type
   var provider = new FileExtensionContentTypeProvider();
   provider.Mappings[".wasm"] = "application/wasm";
   provider.Mappings[".dll"] = "application/dll";

   if (env.IsDevelopment())
   {
      app.UseDeveloperExceptionPage();
   }
   else
   {
      app.UseExceptionHandler("/Home/Error");
   }   
   app.UseDefaultFiles();
   app.UseStaticFiles(new StaticFileOptions{ContentTypeProvider = provider});
   app.UseMvc(routes =>
    {
       routes.MapRoute(
       name: "default",
       template: "{controller=Home}/{action=Index}/{id?}");
    });
}
```

**Comment by FrancoisM** [comment]
You were quick, you were right, you were great!

**Comment by rvhuang** [comment]
Hi, a related question: can we change the default folder other than **dist** with the configuration so the output file can be directly shipped to **wwwroot**? Thank you.
