### ISSUE TITLE
mono.wasm file not found.

### ISSUE THREAD

**Issue by scooby0344** [praeclarum/Ooui#150]
I'm hosting the example xamarin forms with web assembly (https://github.com/praeclarum/Ooui/wiki/Xamarin.Forms-with-Web-Assembly)
on an azure site and when loading the page it says the mono.wasm file is not found but it's clearly there.  

The website is https://oouiholler.azurewebsites.net/.  Any ideas?

![image](https://user-images.githubusercontent.com/8961748/39455046-c2e84f24-4c9b-11e8-963a-064fc7dffc48.png)

![image](https://user-images.githubusercontent.com/8961748/39455105-07e2cba4-4c9c-11e8-81f8-69363a436789.png)

**Comment by zbigniew-gajewski** [comment]
Custom content types? See  [this thread](https://github.com/praeclarum/Ooui/issues/148).

**Comment by scooby0344** [comment]
Thanks @zbigniew-gajewski.  The problem is this my project is just a static site with a few files.  Not a .net core mvc site.  The mono.js file is the one calling a fetch on the wasm file.  In order to fix this I'd have to update the mono.js file.
