### ISSUE TITLE
Requires elevated privileges to open httplistener 

### ISSUE THREAD

**Issue by ocdsoft** [praeclarum/Ooui#152]
I was receiving an access denied error and could not run the basic example in VS 2017 or the CLI, until running via the CLI as administrator.

It worked as expected after running the following in an elevated cmd prompt.

netsh http add urlacl url=http://*:8080/ user=everyone

**Comment by KillerGoldFisch** [comment]
Just as a side note: This command is System-Language dependent!

On a german System you need to execute:

`netsh http add urlacl url=http://*:8080/ user=jeder`

**Comment by PathogenDavid** [comment]
Another workaround is to bind to the loopback interface instead of `*`. IE: `UI.Host = "localhost"`. It might be better to put this in the sample with a note about the issue.

**Comment by garethhubball** [comment]
Would it be worth having `UI.Host = "localhost"` as the default so that this isn't an issue for people getting started?

**Comment by praeclarum** [comment]
Hi everyone. I've taken Gareth's PR to default to "localhost" now.
