### ISSUE TITLE
Using XAML Content Page Build Warning and Blank Page - Question

### ISSUE THREAD

**Issue by davidlsharp1** [praeclarum/Ooui#174]
Ive seen examples from others using an actual XAML file so I am guessing I am doing something incorrectly but whenever I try to do that I get a build warning and then a console error in the browser.  Am I missing something?

I created a MonkeyPage.xaml and I just new it up in the program.cs

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:ooui98"
             x:Class="ooui98.MonkeyPage">

    <StackLayout>
            <Label Text="Welcome to Xamarin.Forms!"
                HorizontalOptions="CenterAndExpand"
                   VerticalOptions="Center"/>
    </StackLayout>

</ContentPage>

```

```
static void Main(string[] args)
        {
            // Initialize Xamarin.Forms
            Forms.Init();

            // Create the UI
            var page = new MonkeyPage();

            // Publish a root element to be displayed
            UI.Publish("/", page.GetOouiElement());
        }

```
The build warning:
`C:\Users\david\.nuget\packages\ooui.wasm\0.10.222\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve method System.Reflection.TypeInfo System.Reflection.IntrospectionExtensions::GetTypeInfo(System.Type) [C:\Users\david\source\repos\ooui98\ooui98\ooui98.csproj]
C:\Users\david\.nuget\packages\ooui.wasm\0.10.222\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve method System.Reflection.AssemblyName System.Reflection.Assembly::GetName() [C:\Users\david\source\repos\ooui98\ooui98\ooui98.csproj]
C:\Users\david\.nuget\packages\ooui.wasm\0.10.222\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve type System.Reflection.AssemblyName [C:\Users\david\source\repos\ooui98\ooui98\ooui98.csproj]
    3 Warning(s)
    0 Error(s)`

The browser console error:
`
ooui.js:435 Error: System.TypeLoadException: Could not resolve type with token 0100000a from typeref (expected class 'System.Reflection.IntrospectionExtensions' in assembly 'Xamarin.Forms.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null')
  at :8000/ooui98.MonkeyPage..ctor () <0x2384300 + 0x00010> in <aa2e9c22d5b44ba4b6e7390ed1e3afa0>:0 
  at ooui98.Program.Main (:8000/System.String[] args) <0x1ef5970 + 0x0000a> in <aa2e9c22d5b44ba4b6e7390ed1e3afa0>:0 
  at :8000/ooui98.MonkeyPage..ctor () <0x2384300 + 0x00010> in <aa2e9c22d5b44ba4b6e7390ed1e3afa0>:0 
  at ooui98.Program.Main (:8000/System.String[] args) <0x1ef5970 + 0x0000a> in <aa2e9c22d5b44ba4b6e7390ed1e3afa0>:0 
    at Object.call_method (ooui.js:404)
    at Object.runApp (ooui.js:428)
    at Object.init (ooui.js:417)
    at Object.init (ooui.js:375)
    at Object.bclLoadingDone (ooui.js:357)
    at ooui.js:350
`

![image](https://user-images.githubusercontent.com/7958760/41074300-09a23468-69cd-11e8-9b04-85e0a6c9aa44.png)

**Comment by zbigniew-gajewski** [comment]
Working examples [here](https://github.com/zbigniew-gajewski/ooui-wasm-aspnet-core-xaml) and [here](https://bitbucket.org/MarkStegaOHI/oouiwxf/src/develop/) (based on ASP .Net Core) where:
1. **Xamarin.Forms v. 2.5** is used (browser error shows Xamarin.Forms.Core 2.0.0.0).
Example 1:
![oouiexample](https://user-images.githubusercontent.com/32226444/41085059-26be8b32-6a36-11e8-9044-e07458a652a0.png)
Example 2:
![oouiexample2](https://user-images.githubusercontent.com/32226444/41085709-160e73f4-6a38-11e8-8344-08a79170709d.png)
2. Custom content types added on server side (**application/wasm**, **application/dll**) - see **Startup.cs** if you are using ASP .Net Core (browser warning shows 'Incorrect response MIME type').

**Comment by davidlsharp1** [comment]
Thank you!  I had seen your notes in other comments but I didnt realize you had a separate asp net core application serving it. I was trying to just use the core console app and use the server.py.  Very cool.

**Comment by adelinmaubray** [comment]
Can't I use Web Server for Chrome to run my index.html file ? 
(I have the same console error in the browser)
