### ISSUE TITLE
Clone issue

### ISSUE THREAD

**Issue by dcuccia** [praeclarum/Ooui#176]
Noob here - this may be a dumb question, but I'm having trouble cloning on a fairly clean Win 10 x64 machine. GitHub complains about an authentication failure. Tried GIT Bash, command line, GitHubDesktop...all the same. See attached:

![ooui_checkout_failure](https://user-images.githubusercontent.com/479617/41206830-7978cd3e-6cbf-11e8-8c91-a8313856158a.PNG)

Error in command line:

> c:\Projects\temp\Ooui>git clone git@github.com:praeclarum/Ooui.git ooui4
> Cloning into 'ooui4'...
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I've successfully cloned other GitHub projects, have re-associated my SSH key with GitHub account, have read the following:

https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey

Am I missing something obvious? Sorry to disturb, just trying to follow the getting started instructions...will download for now.

**Comment by davidlsharp1** [comment]
Out of curiosity, are you using the command line? or in visual studio?

**Comment by davidlsharp1** [comment]
Have you tried both by SSH and HTTPS?

**Comment by dcuccia** [comment]
@davidlsharp1 Thanks for your help. I was mainly trying to use GitHub Desktop x64 for Windows, which I believe is over HTTPS. Interestingly, after installing GitHub Desktop on a new PC, the desktop app continued to fail as above, but the _shell_ shortcut that app installs...

"[user]\AppData\Local\GitHub\GitHub.appref-ms --open-shell"

...opens a PowerShell environment where the clone completes the clone correctly. When I try to do this over the command line, or [bash](https://docs.microsoft.com/en-us/windows/wsl/install-win10), it is still failing with the same message.

**Comment by davidlsharp1** [comment]
@dcuccia Does it even prompt you for the passphrase for your ssh key?

Maybe you try generating a new key and trying that?

**Comment by mallibone** [comment]
In case someone else stumbles over this. I ran into the same issue. The reason is the URI for the submodules uses a ssl certificate instead of https, which requires you to have a [valid certificate](https://help.github.com/articles/connecting-to-github-with-ssh/) for cloning. You can change the line in the modules to go over https. I have made a [pull request ](https://github.com/praeclarum/Ooui/pull/182) containing the single line change. Feel free to apply the change on your local directory.

**Comment by dcuccia** [comment]
@mallibone Very cool, worked for me, thanks! Support this PR.

**Comment by praeclarum** [comment]
I've merged the PR. Sorry for the trouble!
