### ISSUE TITLE
How to use XAML work with Ooui?

### ISSUE THREAD

**Issue by MiyamuraMiyako** [praeclarum/Ooui#177]
Env: VS2017, last version ooui.wasm, netcore sdk 2.1.300

I try add one ContentPage, but 
![image](https://user-images.githubusercontent.com/10345361/41471284-cde71946-70e5-11e8-9d82-6ca764bef30a.png)

**Comment by Happypig375** [comment]
Can you post the error?
Is it 'InitializeComponent cannot be found' or something similar?

If so, try cleaning and rebuilding the project. The XAML codebehind will be automatically regenerated and the error will go away.

**Comment by MiyamuraMiyako** [comment]
![image](https://user-images.githubusercontent.com/10345361/41476221-803febba-70f3-11e8-932c-23398e3458c9.png)
@Happypig375 current context not exist name `InitializeComponent `. I try clean and rebuild project, but still build error.

**Comment by zbigniew-gajewski** [comment]
If you are using Asp.Net Core then [this thread](https://github.com/praeclarum/Ooui/issues/174) might help.
Working examples [here](https://github.com/zbigniew-gajewski/ooui-wasm-aspnet-core-xaml) or [here](https://bitbucket.org/MarkStegaOHI/oouiwxf/src/develop/). Examples contain XAML with binding (MVVM).

**Comment by MiyamuraMiyako** [comment]
The problem began to become strange.
1. Every time I open VS must re-add ooui nuget to compile.
![image](https://user-images.githubusercontent.com/10345361/41500258-eda010e0-71c0-11e8-81dc-fc3360fce24f.png)
![image](https://user-images.githubusercontent.com/10345361/41500240-b9cf6b08-71c0-11e8-9b98-a8965fe6d3d9.png)

2. [this thread](https://github.com/praeclarum/Ooui/issues/174) can't help me.

**Comment by zbigniew-gajewski** [comment]
I have the same issue after downloading it for the first time, but I don't have to re-add packages. 
What I am doing is:
-  right click on the **Solution** level, then click **Restore Nuget pacakges**
- close VS2017 and open it once again 
After opening VS 2017 for the second time, all references are OK.

After compiling, just:
- set **OouiTestWeb** project as a **Sturtup** project and **F5** 
or
- **right click** on the **OouiTestWeb** project and click **Debug** -> **Start new instance** 

You should get something like this:
![image](https://user-images.githubusercontent.com/32226444/41500414-fae15e06-7190-11e8-9f16-f576ddbce682.png)

**Comment by zbigniew-gajewski** [comment]
If you can compile the project, then ignore warnings. 
Just Right click on **OouiTestWeb** project, then **Debug -> Start new instance**.

**Comment by MiyamuraMiyako** [comment]
ok,`OouiTestWeb ` compiled ok.
