### ISSUE TITLE
Cannot cast to Xamarin.Forms.IRegisterable.

### ISSUE THREAD

**Issue by aesalazar** [praeclarum/Ooui#188]
I am trying to use my Xamarin Forms app with Ooui Wasm and I get the following error when calling `page.GetOouiElement()` in static Main:

`
'Unable to cast object of type 'SkiaSharp.Views.Forms.SKCanvasViewRenderer' to type 'Xamarin.Forms.IRegisterable'.'
`

As you can see, this project involves the SkiaSharp libs to do some basic 2D animation.  The page object is a MainPage in the XF app with a single content element I created when is derived from [SKCanvasView](https://docs.microsoft.com/en-us/dotnet/api/skiasharp.views.forms.skcanvasview?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(SkiaSharp.Views.Forms.SKCanvasView);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=skiasharp-views-forms-1.60.3).  I also implement the IRegisterable in the class.

Before I spin my wheels too much I figured I would ask if I am doing something that Ooui is not yet ready for,  Is that the case or should this work in theory?  I can push to a repo if needed.

Thanks
Ernie

**Comment by Happypig375** [comment]
I don't think SkiaSharp has support for platforms other than desktop and mobile. As SkiaSharp uses native libraries under the hood, you can't use it on unsupported platforms. I suggest using custom renderers to render a `SKCanvasView` in a `Ooui.Canvas`.

**Comment by aesalazar** [comment]
@Happypig375  Thanks for that, I get it now.  So, ya, SkiaSharp isnt going to work in this case.  I was looking at the Canvas and it might do it actually.  But I couldnt find any samples how how to use it.

I took a total shot in the dark with this:

`
using Ooui;

namespace Asteroids.Ooui
{
    class Program
    {
        static void Main(string[] args)
        {
            // Initialize Xamarin.Forms
            Xamarin.Forms.Forms.Init();

            // Create the UI
            var canvas = new Canvas();
            canvas.Width = 400;
            canvas.Height = 400;

            canvas.Style.BackgroundColor = new Color(100, 0, 0, 255);
            canvas.Style.Color = new Color(0, 100, 0, 255);
            canvas.Style.FontSize = 12;
                
            var canvas2d = canvas.GetContext2D();
            canvas2d.FillRect(0, 0, 100, 100);
            canvas2d.FillRect(200, 0, 100, 100);

            canvas2d.LineWidth = 4;
            canvas2d.LineTo(300,0);
            canvas2d.LineTo(400,100);

            canvas2d.FillText("Test", 100, 100, 100);

            var form = new Form();
            form.AppendChild(canvas);
            form.Style.BackgroundColor = new Color(100, 100, 100, 255);
            
            // Publish a root element to be displayed
            UI.Publish("/", form);
        }
    }
}
`
Which kind of worked.  I see the grey background color for the canvas, the red foreground color, and the first rectangle.  But I do not see the second rect, line, or text.  Is there any documentation on how to use the Canvas?

Thanks for the help with this!
Ernie
