### ISSUE TITLE
Found WebView show stopper bug, not sure about text not url source re #217

### ISSUE THREAD

**Issue by Psercom** [praeclarum/Ooui#223]
Issue: Buttons etc. on page are dead if page includes a WebView.  No message pump active.
Identified problem:  client javascript was never getting loaded and the ooui entry point in javascript was never called, so the messaging between the dom and backend was nonoperative.
Experience: This remaining bug, now, now fixed, was the one major show stopper in porting a large, complicated XF application to ooui in order to get a web implementation.  The ooui code is clean and beautiful but the bug was hard to find since building and learning the debug code for ooui and Xamarin Forms was time consuming but ultimately not productive given the nature of the html quirk that ultimately solved the problem.  We believe ooui is now ready for prime time, although we haven't yet tested to see if this fix also resolves the webview problem where its source input must be a url rather than raw text.  A problem for another day that won't hold us up now.
Recommendation:  ooui is beatifully conceived, architected and written. Xaml once, publish everywhere.  Fantastic visionary component.  Thanks Frank.
Resolution: Not an ooui bug at all, but standards quirk for html iframe!! Specifically, the opening iframe tag must itself be closed accompanied by a later separate iframe closer, rather than use </> automatic tag closure.  Unbelievable but true.
Fix:  Just add one line at the top of iframe.cs.
    public class Iframe : Element
    {
        // MUST ADD THE FOLL LINE SO IFRAME INITIAL TAG CLOSE for WebView, NEEDED OR JAVASCRIPT WON'T RUN!!! EUREKA!!!!!
        protected override bool HtmlNeedsFullEndElement => true;  // trynew tryin YES EUREKA close initial tag
Regrets:  We've never done a pull request and are in crunch way behind from sleuthing this problem out, so we must leave it others more directly involved to do a pull request.  The ancillary problem of not accepting text input should be resolved and pushed at the same time.

**Comment by Psercom** [comment]
We also loaded javascript and called the entry point outside below the closing </body> tag in ui.cs, although we suspect this isn't necessary.  We haven't reverted to test however.

Running code from ui.cs:

            writer.WriteLine (initialHtml);
            //orig writer.Write(@"</div> next 2 lines replace orig
            writer.Write(@" </div> ");
            writer.WriteLine(@"</body>"); // up  here now js loaded after html body
            writer.Write (@"

<script src=""/ooui.js""></script>
//<script>alert(""geez0"");</script>
//<script>alert(""geez"");ooui(""");
            writer.Write (webSocketPath);
            writer.WriteLine (@""");</script>");
            writer.WriteLine (BodyFooterHtml);
            //split blo            writer.WriteLine(@"</body>
            //</html>");
            //then moved up writer.WriteLine(@"</body>");
            writer.WriteLine(@"</html>");

**Comment by praeclarum** [comment]
Hello, thanks so much for tracking this down. I never would have caught it. Please let me know if this fixes any of the other open bugs.

**Comment by Psercom** [comment]
Hi Frank,

It was hard to find but at all the logical junctures where we might have 
given up, we were enjoying learning the code and really liking the whole 
endeavor so that inspired us to keep on.

Now, however, we did go back and flip on our test to see if WebView 
works from raw text as opposed to url input.  Unfortunately, it doesn't 
even when we verify the other tag closure fix is active (buttons etc. 
are active).

So these are separate bugs.

We are hoping this second one might be easy for you to see and fix, 
knowing the code thoroughly.

Thanks for everything.

Larry
