### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by kellcomnet2** [praeclarum/Ooui#235]
Is this project still alive?

**Comment by scottkuhl** [comment]
The silence is deafening. Wild guess that Microsoft is planning official support for Xamarin Forms on the web.

**Comment by robertsundstrom** [comment]
@kellcomnet2 @scottkuhl 

A bit late but...

The Uno Platform (UWP-compatible UI framework) have their own binding to Xamarin.Forms. They are more invested in this at the moment. 

They have a sample running on WebAssembly.

They even credited Frank (@praeclarum) for his work on the bootstrapper that they refined for Uno.

Read their announcement for Xamarin.Forms bindings:

https://platform.uno/announcing-uno-platform-2-0/

**Comment by praeclarum** [comment]
Thank you all for your support. Ooui is a lot more than just Xamarin Forms on the web.
