### ISSUE TITLE
location.reload() when WebSocket closed disrupts user experience

### ISSUE THREAD

**Issue by fubar-coder** [praeclarum/Ooui#24]
I tried to simulate a bad network connection by disabling my network adapter. This caused - in FF 57 and Chrome 62 - the `close` event for the WebSocket to be called.

Is this behavior by design? I haven't tested yet how the mobile versions of FF and Chrome handle network losses on mobile devices and the behavior might be different there.

**Comment by praeclarum** [comment]
No that doesn't sound right. I haven't spent much time working on the logic for re-establishing coms. So far, I just manually refresh to do it (which generates a new session).

I am very much open to ideas on how to handle specific disruptions. I guess getting your common case of temporarily losing a connection working should be the first step.

**Comment by praeclarum** [comment]
After reviewing - yes I do remember adding this code because I didn't want people to think the site is live. But now I think it would be better to just show an error if they try to interact.
