### ISSUE TITLE
cannot build from CLI or VS Code

### ISSUE THREAD

**Issue by bitbonk** [praeclarum/Ooui#26]
First of all, thank you for this beautiful little piece of technology!

When I try to compile and run the sample using the VS Code or using the dotnet cli directly

```batch
dotnet run --project Samples/Samples.csproj
```

I get the below error.

> C:\Users\bitbonk\.nuget\packages\xamarin.forms\2.4.0.38779\build\netstandard1.0\Xamarin.Forms.targets(51,3): error MSB4062: The "Xamarin.Forms.Build.Tasks.FixedCreateCSharpManifestResourceName" task could not be loaded from the assembly C:\Users\bitbonk\.nuget\packages\xamarin.forms\2.4.0.38779\build\netstandard1.0\Xamarin.Forms.Build.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\temp\Ooui\Ooui.Forms\Ooui.Forms.csproj]
> The build failed. Please fix the build errors and run again.

When I build and run from Visual Studio 2017, everything works fine.

[This issue](https://github.com/dotnet/cli/issues/5457) might be related.
Also: [this](https://stackoverflow.com/questions/47143795/building-net-standard-application-that-references-xamarin-forms).

**Comment by praeclarum** [comment]
Yes I have run into this too, but so far only on Linux.

I filed a bug against Xamarin Forms for including an SDK reference in a .NET Standard project instead of the nuget reference. 

https://bugzilla.xamarin.com/show_bug.cgi?id=60705

As a workaround, I build the app with mono's msbuild. And then I run with `dotnet run --no-build`

Obviously this is not great. I'll see if we can get Xamarin to fix their build.

**Comment by praeclarum** [comment]
Looks like there is a Xamarin Forms PR to fix this: https://github.com/xamarin/Xamarin.Forms/pull/1284

**Comment by ahoefling** [comment]
@bitbonk if you are interested in vs code settings to use while we wait for the PR to be merged check out my referenced commit in my fork. Since this is going to be fixed soon I'm not planning to submit a PR but the settings work for me on linux for compiling and debugging

**Comment by praeclarum** [comment]
Looks like a fix got merged. Just have to wait for a release to include it.

**Comment by praeclarum** [comment]
I tried with 2.5.0.122203 and it's still failing: https://github.com/xamarin/Xamarin.Forms/issues/1777

**Comment by praeclarum** [comment]
Did 3.0 work?

**Comment by mcintyre321** [comment]
Can't see 3.0.0.0 on Nuget?  

I've removed Xamarin.Forms for now and am just using the OOui elements, which are fine for what I'm doing.

**Comment by praeclarum** [comment]
Make sure you check the box to see pre-release. It’s unfortunate, but we’re all stuck waiting for it to come out.

**Comment by mcintyre321** [comment]
Yep, I tried `3.0.0.354232-pre3` which is a prerelease. I'll give it another go, maybe something went wrong with my push to bitbucket/azure.

**Comment by praeclarum** [comment]
I’m pushing OouiChat to Azure, maybe checkout my settings and versions.

https://github.com/praeclarum/OouiChat <https://github.com/praeclarum/OouiChat>
