### ISSUE TITLE
Instructions on how to run the xamarin forms samples

### ISSUE THREAD

**Issue by EmmanVazz** [praeclarum/Ooui#27]
This looks great. I can run the normal samples but can't figure out what url to hit to see the forms samples in the project.

**Comment by jamesmontemagno** [comment]
Set the ASP.NET Core as your startup and there is a link to them:

![image](https://user-images.githubusercontent.com/1676321/32911986-9bb9bed4-cac2-11e7-82a1-db5abfccf186.png)

**Comment by EmmanVazz** [comment]
Thanks! Mind blown. 
https://media.giphy.com/media/EldfH1VJdbrwY/giphy.gif
