### ISSUE TITLE
What are the odds of merging this with Xamarin.Forms as a new backend?

### ISSUE THREAD

**Issue by Happypig375** [praeclarum/Ooui#33]
This will benefit all Xamarin.Forms developers.

**Comment by psmulovics** [comment]
This is with Xamarin.Forms as a backend. Read the intro post at http://praeclarum.org/post/167525842703/xamarin-forms-on-the-web

**Comment by Happypig375** [comment]
I mean merging with the [Xamarin.Forms codebase](https://github.com/xamarin/Xamarin.Forms) as something like Xamarin.Forms.Platform.Web or Xamarin.Forms.Platform.Ooui.

**Comment by praeclarum** [comment]
I don't see the point in burdening the Xamarin.Forms team. They designed XF to be extensible and this library extends it - we should leave it at that.

**Comment by Happypig375** [comment]
Fine...
