### ISSUE TITLE
Web sockets sometimes fails to connect with 400 Bad Request

### ISSUE THREAD

**Issue by praeclarum** [praeclarum/Ooui#36]
From Twitter

https://twitter.com/tonyvca/status/932003039757721602

![do8jsatxkau3w3l jpg-large](https://user-images.githubusercontent.com/323548/32985217-4dd7d38a-cc7b-11e7-9e56-b92589cf0695.jpeg)

**Comment by TonyHenrique** [comment]
![image](https://user-images.githubusercontent.com/6307623/32985470-afa558fc-cc9a-11e7-930c-3165c0172e3f.png)

This site says I am not behind a proxy, but I am not sure.

**Comment by praeclarum** [comment]
BadRequests now return an error string. If this happens again, please inspect the response text to see the actual error.

**Comment by TonyHenrique** [comment]
![image](https://user-images.githubusercontent.com/6307623/33244807-8b0ac8ae-d2dc-11e7-8060-1263b344f9fe.png)

**Comment by praeclarum** [comment]
Thanks for the info! Unfortunately the error is in the *content* of the response (the "response text") - not in the headers and your screenshot doesn't show that.

So sorry you're still having this problem - we'll find it :-)

**Comment by TonyHenrique** [comment]
I tried again today and now it works.

**Comment by praeclarum** [comment]
Oh thank goodness. Please re-open if I ever regress.
