### ISSUE TITLE
Add Default Styling for Buttons

### ISSUE THREAD

**Issue by ahoefling** [praeclarum/Ooui#37]
Currently buttons require additional styling to look right on the screen. If you don't explicitly set the bootstrap styles or the `HeightRequest = 30` (give or take a little with the number 30) the button will be smaller than the text and not look correctly. 

Current Button Behavior:
![image](https://user-images.githubusercontent.com/17751436/32992819-5cb0fd44-cd1d-11e7-9f93-7dab0ec3c8ca.png)

XAML:
```xml
<Button />
```

Recommended Fix:
Since it has been discussed in #32 that we are going to take the dependency of Bootstrap I think it would be appropriate to apply the styles to the Button Renderer.

This is something I can take and submit a PR for

**Comment by ahoefling** [comment]
Added a change in my fork that should fix it, I'll test it later and submit a PR

**Comment by praeclarum** [comment]
Oh great, I was meaning to do this. Also need to fix the code that calculate the height.

**Comment by ahoefling** [comment]
@praeclarum I added a default Height Style but it doesn't seem to be working. Can you point me towards the code that implements HeightRequest so I can see how the Button.Style.Height is used or what the HeightRequest uses. 

I spent some time digging through this and I couldn't figure it out. I know you said you want to add some code to calculate the height, I was planning just to hard code a default height in for now.

**Comment by praeclarum** [comment]
Heights are calculated in multiple levels in Xamarin Forms. At the lowest level, the Extension method `GetSizeRequest` is called to get the default HTML size for things. Forms uses this when it doesn't have any other requests. 

https://github.com/praeclarum/Ooui/blob/master/Ooui.Forms/Extensions/ElementExtensions.cs#L8 is 

However you can override `GetDesiredSize` https://github.com/praeclarum/Ooui/blob/master/Ooui.Forms/IVisualElementRenderer.cs#L18

to scale the default size (which just measures the text). For now, you can just scale the base height:

```csharp
var size = base.GetDesiredSize (...);
size.Request = new Size (size.Width, size.Height * 1.4);
return textSize;
```

That will be a bit better than hard coding a constant. You can play with the `1.4` to be closer to whatever bootstrap uses. But keep it simple for now - I need to study bootstrap's style sheet to understand how to calculate it for real.

**Comment by praeclarum** [comment]
Also you should be able to use `Style.Height` - the trick is you have to specify units or the DOM ignores it (more strict than CSS). I changed the Style class to handle this for you - just make sure to rebase to master.

**Comment by praeclarum** [comment]
I ended up implementing this myself (as I was getting tired of the bad sizes).

https://github.com/praeclarum/Ooui/commit/e085f236b6b201aef5b3c1d799c1bf97e3fda686
