### ISSUE TITLE
Select element not implemented fully?

### ISSUE THREAD

**Issue by mcintyre321** [praeclarum/Ooui#40]
Hi, really enjoying the project, great idea.

I'm trying to use a select element, but I'm not sure it's fully implemented. I couldn't find an Option type, so I had to define one:

```
public class Option : Element
{
	public Option()
		: base("option")
	{
	}

	string _value = "";
	public string Value 
	{
		get => _value;
		set => SetProperty(ref _value, value ?? "", "value");
	}
}
```
but then I couldn't find a way to get the SelectedIndex of the current element from the Select in the ChangedHandler, and the Selects `Value` property is null, even with an item selected . Am I doing it wrong?

**Comment by praeclarum** [comment]
You're doing it right, but there is something going on that I don't understand.

I'll have to write a test to understand what's missing.

**Comment by praeclarum** [comment]
I fixed the Value property of Select to read the right values. Please see the Draw sample for an example of its use.

**Comment by mcintyre321** [comment]
Thanks!
