### ISSUE TITLE
Switch does not fire change event

### ISSUE THREAD

**Issue by bjorndaniel** [praeclarum/Ooui#48]
It seems as though the node.addEventListener(m.k... event is not being triggered by the bootstrap.toggle?
If the code is changed to use jquery $(node).on(m.k... it works as expected.
Is this a known issue or am I missing something?

**Comment by praeclarum** [comment]
Would you give me a code sample to try? Specifically, which Ooui object are you instantiating?

**Comment by bjorndaniel** [comment]
Here's an example of what I'm trying to do:
https://github.com/bjorndaniel/SwitchError
What I would like to happen is for the label to change on toggle, and this does happen if I high-jack your node.addEventListener and instead add jquerys listener using $(node).on
I find this weird since they should behave the same way, but it is js after all...
