### ISSUE TITLE
Socket Closes when navigating away and back to page

### ISSUE THREAD

**Issue by jamesmontemagno** [praeclarum/Ooui#52]
In Chrome

1.) http://soundbitefm.azurewebsites.net/
2.) Click on podcast art
3.) hit back in browers
4.) white screen

Web socket created
ooui.js:46 WebSocket connection to 'ws://soundbitefm.azurewebsites.net/ooui.ws?id=ec584595b3b64d00a35977d6aaf659aa&w=1920&h=949' failed: Error during WebSocket handshake: Unexpected response code: 400
ooui @ ooui.js:46
ooui.js:54 Web socket error Event
(anonymous) @ ooui.js:54
ooui.js:58 Web socket close CloseEvent
(anonymous) @ ooui.js:58
ooui.js:110 WebSocket is already in CLOSING or CLOSED state.

**Comment by praeclarum** [comment]
Thanks! I didn't catch this because Safari doesn't turn everything white. Not sure why Chrome is freaking out.

The code needs to add re-connection logic. Working on it...

**Comment by DIGIHOME-MK** [comment]
The same problem with Edge on Windows Mobile 10

**Comment by jamesmontemagno** [comment]
I seem to still be getting this :(

Works on Edge normal Windows 10 though
