### ISSUE TITLE
Is ListView implemeted?

### ISSUE THREAD

**Issue by SuperJMN** [praeclarum/Ooui#53]
Hello! I'm new to this wonderful project and I'm playing around with it to see what works and what does not. 

For now, I've put this XAML:

```
<ListView ItemsSource="{Binding People}" >
    <ListView.ItemTemplate>
        <DataTemplate>
            <TextCell Text="{Binding Name}" />
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
```
But nothing is rendered in the web browser.

I think that ListView isn't supported yet. Otherwise, how do I use it? Thank you!

**Comment by jamesmontemagno** [comment]
It is not, see: https://github.com/praeclarum/Ooui/tree/master/Ooui.Forms/Renderers

**Comment by praeclarum** [comment]
Yeah it's a gaping hole.

**Comment by jsuarezruiz** [comment]
Well, work in progress...
![ooui listview](https://user-images.githubusercontent.com/6755973/34563235-1f80d9ea-f152-11e7-8e89-6d14dde3d3a1.gif)
I think we'll have a basic implementation soon (no groups, etc.)

**Comment by SuperJMN** [comment]
It already looks great! it will allow a lot of nice samples now :) If it supports binding to `SelectedItem`, then it's going to be wild.

**Comment by jsuarezruiz** [comment]
Sent PR: https://github.com/praeclarum/Ooui/pull/59

**Comment by praeclarum** [comment]
Thanks @jsuarezruiz - it's a great. I'll try to put some time in getting other bits implemented.
