### ISSUE TITLE
System.TypeLoadException: 'Method 'QuitApplication' in type 'OouiPlatformServices' from assembly 'Ooui.Forms, Version=0.5.123.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

### ISSUE THREAD

**Issue by TonyHenrique** [praeclarum/Ooui#55]
I followed *almost all* the instructions on https://montemagno.com/building-a-xaml-xamarin-forms-asp-net-website/

added the lines

```
app.UseOoui();
Xamarin.Forms.Forms.Init();
```
But got this exception on Xamarin Forms Init():

`System.TypeLoadException: 'Method 'QuitApplication' in type 'OouiPlatformServices' from assembly 'Ooui.Forms, Version=0.5.123.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'`

```
Xamarin.Forms   2.5.0.121934
Ooui    	0.5.123
Ooui.AspNetCore 0.5.123
Ooui.Forms    	0.5.123
```

**Comment by jamesmontemagno** [comment]
Like I said, you MUST install the exact version that Ooui needs, which is 2.4.0.38779

**Comment by jamesmontemagno** [comment]
I uploaded my code: https://github.com/jamesmontemagno/MyFirstOouiApp

**Comment by TonyHenrique** [comment]
I Consolidated the Xamarin.Forms NuGet packages to version 2.4.0.38779 across my solution and it Works.

**Comment by praeclarum** [comment]
Unfortunately there was a breaking change to Xamarin.Forms 2.5 - I guess it should have been Xamarin Forms 3.

I guess I will have to require 2.5 from now on...

**Comment by jamesmontemagno** [comment]
yea! do it!

**Comment by SuperJMN** [comment]
No worries. Go ahead! My life is an Early Preview ;)
