### ISSUE TITLE
TypeScript or JQuery

### ISSUE THREAD

**Issue by grahamehorner** [praeclarum/Ooui#56]
Please consider removing any dependency on jquery and/or implementation using TypeScript to provider better developer experience with strong typing, intelligence and other features that TypeScript provides such ECMA script compliance and NULL check as the project size increase this will also ease any pain with regards to testing and introducing any issues.

**Comment by wcoder** [comment]
or use https://github.com/praeclarum/Netjs if it possible

**Comment by praeclarum** [comment]
Which experience are you trying to improve with TypeScript?

**Comment by grahamehorner** [comment]
using TypeScript would remove the need for jQuery and give a better developer experience with strong typing and enforce type checking, it would also allow better cross-platform support with regards to enabling features of new ECMA by creating polyfills for the browser

**Comment by praeclarum** [comment]
We only require jQuery for a simple switch control - no logic is executed there.

C# gives excellent type checking support.

I'm going to close this issue because it sounds like you want something quite different and incompatible with Ooui.
