### ISSUE TITLE
work without asp.net?

### ISSUE THREAD

**Issue by halukmy** [praeclarum/Ooui#66]
i just wonder is it possible to run at .net core on raspbian without asp.net core? :)

thats sounds crazy but wonder possible? :)

**Comment by praeclarum** [comment]
Absolutely. You just need to install ".NET Core" runtime.

Unfortunately, the SDK isn't supported (help me yell at Microsoft) so you will have to compile on a different machine.

Just publish your elements:

```UI.Publish(new Button())```

I built Ooui to run on Raspbian ;-)

**Comment by halukmy** [comment]
ouuuiiiiiiiiii :))

im kinda new on linux thing, i work with awesome with console app but if oui runs without asp core thats cooooll

sooo ermmm can anyone share how to with .net core on ubuntu?? :)

**Comment by ahoefling** [comment]
I believe there was a pull request recently submitted about using the CLI to build and run. Basically you need to have the mono compiler and then you execute the following commands

```
msbuild
dotnet run --no-build
```

Right now there is a known issue in Xamarin.Forms and using the `dotnet build` command so using the mono compiler works just fine.

This is how I run Ooui on my ubuntu machine

**Comment by halukmy** [comment]
@ahoefling how you configure port for outside connection?

forexample http://ouiiapp.com:9898 

to configure that port? possible?

**Comment by jamesmontemagno** [comment]
You do not need to at all. You just need to make sure you turn on web sockets.

**Comment by praeclarum** [comment]
@halukmy If you're using the built-in server, then you just need to set `UI.Port`

**Comment by halukmy** [comment]
@praeclarum is there any example? :) thanks

**Comment by Mike-EEE** [comment]
> You just need to make sure you turn on web sockets.

You mean on the .NET side or on the browser side?  Or both? 😛   Web Sockets are already turned on in most modern browsers by default, correct?  So it's just a matter of creating one on the .NET side, if I understand this correctly.
