### ISSUE TITLE
Question: Trigger.io Support?

### ISSUE THREAD

**Issue by Mike-EEE** [praeclarum/Ooui#74]
Pretty nifty project here. 😄 

Curious if you know if this integrates well with Trigger.io:
https://trigger.io/

Or is there another/known/preferred method for running this in a native context?

**Comment by praeclarum** [comment]
This is my first exposure to Trigger. Can you give me some context as to how an app would be architected?

**Comment by Mike-EEE** [comment]
I just learned of it as well. 😆 It's basically the same as PhoneGap, and allows you to package a web application as a native application and gives you access to native resources (camera, GPS, etc.).

In your readme it states that Ooui can run "everywhere", but you really mean within a web context, correct?  Is there a way to run Ooui in a native context as well?

**Comment by praeclarum** [comment]
Ooui can run anywhere .NET can - that's it's only limitation. Since Trigger is JavaScript based, getting the two to work together would not be very sustainable. I'm going to close this because I doubt I'll implement it. But thanks for the pointer, I'll keep an eye on it!

**Comment by Mike-EEE** [comment]
OK cool.  I am actually interested in exploring this. :)  I will contact the Trigger team to see if it's possible to somehow host an HTTP listener locally (along with Xamarin-compiled artifacts).

**Comment by Mike-EEE** [comment]
WOW... this is actually way easier than I thought.  There is no need to use Trigger/PhoneApp/Cordova for packaging/deployment.  I simply created a native project with a simple Xamarin Forms with a WebView as such:
https://github.com/Mike-EEE/Ooui/blob/master/PlatformSamples/Native/Native/MainPage.xaml#L8

And then a publish call here as such:
https://github.com/Mike-EEE/Ooui/blob/master/PlatformSamples/Native/Native.UWP/MainPage.xaml.cs#L11

And whalah, instant magic. 😄 

I think this is a powerful example as it demonstrates your awesome library here working within a native context.  Let me know if it makes sense to work with you on a PR to make this happen (and/or if we should open a new ticket).

BTW, this technically satisfies the requirements for a very popular ask here:
https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/10027638-create-a-ubiquitous-net-client-application-develo

**Comment by Mike-EEE** [comment]
FWIW, I am running into confusion whether or not this is actually possible in a deployed hosted store environment.  As per above it appears to run just fine in a local development UWP environment, but that doesn't verify that it actually works when deployed to the actual UWP store, or Apple or Droid's for that matter.

I have a question outstanding here on Xamarin's forum if anyone can please clear up my confusion:
https://forums.xamarin.com/discussion/124126/does-httplistener-work-in-native-store-hosted-environments/p1

Thank you for any assistance you can provide. 😄

**Comment by birbilis** [comment]
Windows Store also supports Hosted Web Apps, where you just have an empty project and the info for the webpage to show is in the manifest (set in the properties of the project). In latest Visual Studio it is very straightforward, I think you just use the respective project template

Also for other platforms, could use Manifold.js to make a hosted web app, however Xamarin (or Delphi or other IDE that allows you to make a native app that just contains a webview) is a good option too
