### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by danfma-daitan** [praeclarum/Ooui#84]
Apparently, the server only supports Chrome, failing with Firefox. Do you plan to support other browsers?

**Comment by Mike-EEE** [comment]
FWIW I was able to view http://ooui.mecha.parts just fine in Edge and FireFox.  Is there another scenario you are describing here?

**Comment by danfma-daitan** [comment]
hummm... I will provide you later with a project for reproducing this behavior.

**Comment by danfma** [comment]
Try with this! I don't know if this is really possible, but it works on Chrome.

[OouiPlayground.zip](https://github.com/praeclarum/Ooui/files/1791265/OouiPlayground.zip)

**Comment by praeclarum** [comment]
I test with Safari and Chrome and will make sure to start testing Firefox. I'm not sure what could be causing issues - perhaps the network was blocking the web socket?

**Comment by danfma** [comment]
Good question! I will try to track better the problem and then I will put the information here.

**Comment by praeclarum** [comment]
I tested on the latest Firefox and it was all working for me. Is it still failing for you?

**Comment by danfma** [comment]
I think you can close this ticket. Apparently, it's working on Firefox now!

**Comment by Mike-EEE** [comment]
@danfma these are the types of bugs and solutions that we as developers strive for.  You're living the dream, brogrammer. 😆

**Comment by praeclarum** [comment]
I've heard rumors that corpnets can block dlls and sometimes wasms. It could have been that too. Yep, the mysteries of the web.

**Comment by psmulovics** [comment]
More than a rumor :(
![image](https://user-images.githubusercontent.com/28162552/37521521-742f88d8-28f7-11e8-8060-2fcac2c4ae42.png)
