### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by ravinderjangra** [praeclarum/Ooui#85]
@praeclarum  Do you have any todo list or priority list?
I would love to work on Xamarin.Forms part.

**Comment by jsuarezruiz** [comment]
You can see Issues labeled as **enhancements**.
On the other hand, if you have something in mind that is not registered, you can create an Issue and Frank and the community will help and review it.

**Comment by praeclarum** [comment]
Thank you for your interest. We now have status doc that you can choose from. https://github.com/praeclarum/Ooui/blob/master/Documentation/OouiFormsStatus.md

Thanks for helping!
