### ISSUE TITLE
Status Documentation

### ISSUE THREAD

**Issue by jsuarezruiz** [praeclarum/Ooui#87]
Hi,

I think it would be interesting to have a documentation section with Ooui Xamarin.Forms **Status**. I have a sample of Xamarin.Forms GTK backend Status: https://github.com/jsuarezruiz/forms-gtk-progress/blob/master/Status.md

![imagen](https://user-images.githubusercontent.com/6755973/37368740-625a9f90-2707-11e8-834e-b4f19df19889.png)

Makes sense?. I can send PR :)

Regards.

**Comment by praeclarum** [comment]
Oh please yes.

I thought I could get it done myself but have failed so far :-)

**Comment by jsuarezruiz** [comment]
Oh, nothing many things to do, no problem. 
I have sent PR: https://github.com/praeclarum/Ooui/pull/91 ;)
