### ISSUE TITLE
Replace server.py with something a little more .NET

### ISSUE THREAD

**Issue by praeclarum** [praeclarum/Ooui#88]
This static page server is used to make sure wasm files get the right content type and to enable XmlHttpRequests for the assemblies.

Python servers are fine for Linux and Mac, but don't work by default on Windows.

Let's replace it with a nice .NET script instead.

An F# script would be perfect, but I worry if that is too intimidating for C# devs.

Alternatively, maybe a `dotnet` tool or run configuration or some other magic could be used.

**Comment by psmulovics** [comment]
C# devs love F# ;)

**Comment by jrgcubano** [comment]
Great idea @praeclarum with Forms!

The server.py example is for python 2, so if anyone out there is trying with python 3:

```python
import http.server
import socketserver

PORT = 8000

class Handler(http.server.SimpleHTTPRequestHandler):
    pass

Handler.extensions_map['.wasm'] = 'application/wasm'

httpd = socketserver.TCPServer(("", PORT), Handler)

print("serving at port", PORT)
httpd.serve_forever()
```

**Comment by hoetz** [comment]
Maybe this can be used instead https://github.com/natemcmaster/dotnet-serve

**Comment by praeclarum** [comment]
@hoetz I saw that this morning! Yeah I will definitely check it out.

**Comment by praeclarum** [comment]
I've tried it out and dotnet-serve works well! Need to update the guides...

**Comment by praeclarum** [comment]
Updated the wiki

**Comment by psmulovics** [comment]
You still need to update 7. in the wiki :)

**Comment by praeclarum** [comment]
Thanks!

**Comment by MarcosCobena** [comment]
Hi guys,

Just to give ever another option if don't want to update .NET Core to its preview or have already installed Python 3.x like me :-)

Simply use "xsp4" bin from Mono's distribution to run a local server from CLI. In macOS, you can already type this if have Xamarin installed. In Windows, simply point to mono-project.org and download it.

Thanks!

-Marcos
