### ISSUE TITLE
More aggressive linking for web assembly

### ISSUE THREAD

**Issue by praeclarum** [praeclarum/Ooui#89]
Right now the linker is using `CopyUsed` as its link setting instead of `Link`. This is because Json.net wasn't working - some part of `System.Linq.Expressions` kept failing.

https://github.com/praeclarum/Ooui/blob/afad957520c65b8b59db06e2ba45e34c003d7814/Ooui.Wasm.Build.Tasks/BuildDistTask.cs#L123-L124

Need to investigate why since the linker can really shrink apps to fractions of their current size.

**Comment by Terricide** [comment]
I recommended simplejson to the blazor project and it is in there right now. It is more lightweight then json.net fyi

**Comment by praeclarum** [comment]
Oh yes, I can always replace Json.NET, but the truth is users of this library won't haha. People love it. So I would rather support it than work around it.
