### ISSUE TITLE
Name wasm files something other than .dll

### ISSUE THREAD

**Issue by psmulovics** [praeclarum/Ooui#92]
If you are on a corporate networks, despite the fact that these files would serve up wasm and not dll binaries, they would be blocked just based on the URL's extension.

**Comment by praeclarum** [comment]
Ugh corpnets. Thanks for the info. I've been considering bundling them all into another file - will make sure not to use DLL for that file.

**Comment by psmulovics** [comment]
Any chance this would be picked up?

**Comment by praeclarum** [comment]
I'll try to get it in the next version.

**Comment by psmulovics** [comment]
Hurray! Thank you!
