### ISSUE TITLE
WASM Reflection.MethodBase is missing

### ISSUE THREAD

**Issue by praeclarum** [praeclarum/Ooui#96]
It would seem that the mscorlib that ships with mono's wasm support is missing the older reflection types.

> Could not resolve type with token 0100000a from typeref (expected class 'System.Reflection.MethodBase' in assembly 'Csla, Version=4.7.100.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30')

```
[Error] Error: System.TypeInitializationException: The type initializer for 'Ooui.Wasm.Test.Person' threw an exception. ---> System.TypeLoadException: Could not resolve type with token 0100000a from typeref (expected class 'System.Reflection.MethodBase' in assembly 'Csla, Version=4.7.100.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30')
   --- End of inner exception stack trace ---
  at Ooui.Wasm.Test.Program.GetButtonElement () <0x772238 + 0x00014> in <42312de6b379496da5205cd71073e56e>:0 
  at Ooui.Wasm.Test.Program.Main () <0x1996a40 + 0x00002> in <42312de6b379496da5205cd71073e56e>:0 
	runApp (ooui.js:441)
	init (ooui.js:423)
	init (ooui.js:381)
	bclLoadingDone (ooui.js:363)
	(anonymous function) (ooui.js:356)
	promiseReactionJob
```

**Comment by rockfordlhotka** [comment]
I am encountering this issue when using [CSLA .NET](https://github.com/marimerllc/csla/). The latest pre-release in NuGet supports Xamarin Forms via netstandard 2.0, and so it seems like it should work.

I followed the steps in this blog post to get a [webassembly XF project working in VS](http://www.lhotka.net/weblog/XamarinFormsAndWebAssembly.aspx), hosted via python in WSL (though the host shouldn't matter).

Then I added a reference to the CSLA .NET pre-release via NuGet (the CSLA-Core.NS package).

Then I added a `Person.cs` class to the project that uses CSLA:

```c#
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Text;
using Csla;

namespace MyFormsApp
{
    [Serializable]
    public class Person : BusinessBase<Person>
    {
      public static readonly PropertyInfo<string> NameProperty = RegisterProperty<string>(c => c.Name);
      public string Name
      {
        get { return GetProperty(NameProperty); }
        set { SetProperty(NameProperty, value); }
      }

      protected override void DataPortal_Create()
      {
        using (BypassPropertyChecks)
        {
          Name = "Teresa";
        }
      }
    }
  }
```

In `Program.cs` I try to create an instance of this type:

```
  var obj = new Person();
```
At this point the code won't build properly. 

```
1>C:\Users\rocky\.nuget\packages\ooui.wasm\0.8.186\build\netstandard2.0\Ooui.Wasm.targets(17,3): error : Error processing method: 'System.Void MyFormsApp.Person::.cctor()' in assembly: 'MyFormsApp.dll'
1>Done building project "MyFormsApp.csproj" -- FAILED.
```

**Comment by praeclarum** [comment]
I was able to expose the actual error:

```
[Error] Error: System.TypeInitializationException: The type initializer for 'Ooui.Wasm.Test.Person' threw an exception. ---> System.TypeLoadException: Could not resolve type with token 0100000a from typeref (expected class 'System.Reflection.MethodBase' in assembly 'Csla, Version=4.7.100.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30')
   --- End of inner exception stack trace ---
  at Ooui.Wasm.Test.Program.GetButtonElement () <0x772238 + 0x00014> in <42312de6b379496da5205cd71073e56e>:0 
  at Ooui.Wasm.Test.Program.Main () <0x1996a40 + 0x00002> in <42312de6b379496da5205cd71073e56e>:0 
	runApp (ooui.js:441)
	init (ooui.js:423)
	init (ooui.js:381)
	bclLoadingDone (ooui.js:363)
	(anonymous function) (ooui.js:356)
	promiseReactionJob
```

Not sure why that type is missing. Still investigating...

**Comment by praeclarum** [comment]
I think I know what's going on. The mono wasm I'm using is built against the old Silverlight profile which uses TypeInfo instead of Type - that is it's a .NET Standard 1.X profile.

**Comment by DanielRRegner** [comment]
Could the old Silverlight profile also be the source of the issues seen in #98 where `HttpClient` and `async`/`await` in general trigger errors due to the `Task<T>` type being missing?


```
1>C:\Users\...\.nuget\packages\ooui.wasm\0.9.206\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve type System.Threading.Tasks.Task`1
1>C:\Users\...\.nuget\packages\ooui.wasm\0.9.206\build\netstandard2.0\Ooui.Wasm.targets(17,3): warning : Failed to resolve method System.Threading.Tasks.Task System.Threading.Tasks.Task`1<System.Net.Http.HttpResponseMessage>::ContinueWith(System.Action`1<System.Threading.Tasks.Task`1<!0>>)
```

**Comment by praeclarum** [comment]
@DanielRRegner That was my original theory, but it's in doubt as the assemblies do seem to contain the types. 

I was told to try these logging levels:

```bash
setenv MONO_LOG_MASK=type
MONO_LOG_LEVEL=debug
MONO_LOG_MASK=asm
```

**Comment by rockfordlhotka** [comment]
Any movement on this issue?

**Comment by praeclarum** [comment]
I think about it all the time? :-) Sorry for the delays, I need a day to study what the linker is doing with those assemblies. The mono people are pretty sure the problem is on my end. I’ll try to look into it this weekend.

**Comment by rockfordlhotka** [comment]
Thank you Frank, I appreciate it! I suspect it is on your end, as I've been able to get CSLA working in Blazor with a few tweaks (relative to `System.Linq.Expressions` and `HttpClient` limitations).

**Comment by DanielRRegner** [comment]
Could it be the case where although the types are present, they are being referenced from the wrong assembly?

For example, with the `System.Activator` type, displaying `typeof(Activator).FullName` works, and in the IL, I see that the type is being referenced from `System.Runtime.dll`, which has a `TypeForwardedToAttribute` back to `mscorlib.dll`.

But when using types that fail to resolve such as `System.Reflection.MethodBase` or `System.Threading.Tasks.Task`, those are also being referenced from `System.Runtime.dll` without any matching  `TypeForwardedToAttribute` back to `mscorlib.dll` where they really reside.

**Comment by praeclarum** [comment]
@DanielRRegner Yes I believe mono is missing some forwarders. I have worked around it in the linker and filed a bug over at mono.

**Comment by praeclarum** [comment]
I have worked around this in https://github.com/praeclarum/Ooui/commit/0877dfb7df7960af3872d03c2aef0717ac0e78be

The CSLA example now works.
