### ISSUE TITLE
WASM Async await not working

### ISSUE THREAD

**Issue by 5yunus2efendi** [praeclarum/Ooui#98]
This is what I use to get started:
```csharp
namespace OouiForms2
{
    class Program
    {
        static void Main(string[] args)
        {
            // Initialize Xamarin.Forms
            Forms.Init ();

            // Create the UI
            var page = new ContentPage();
            var stack = new StackLayout();
            var button = new Xamarin.Forms.Button {
                Text = "Click me!"
            };
            stack.Children.Add(button);
            var activityIndicator=new  ActivityIndicator();
            stack.Children.Add(activityIndicator);
            page.Content = stack;

            // Add some logic to it
            var count = 0;
            button.Clicked += async (s, e) => {
                count++;
                button.Text = $"Clicked {count} times";
                activityIndicator.IsRunning=true;
                await Task.Delay(5000);
                activityIndicator.IsRunning=false;
            };

            // Publish a root element to be displayed
            UI.Publish("/", page.GetOouiElement());
        }
    }
}
```

It seems that when I use async await it give me an error:
![capture](https://user-images.githubusercontent.com/19399214/37505339-ef1087d6-2916-11e8-8535-e63e3fcf4145.PNG)

but when I remove the `await Task.Delay(5000);`, the error is gone. is this a bug or am I missing something?
I use both `dotnet build` and `msbuild /t:build`, but still shows same error

BTW, great job for making this!

**Comment by juanfranblanco** [comment]
I have the same issue trying to make an async HTTP request. 

On another topic, Is this going to need an injected HttpClient like Blazor? Maybe this may another issue in the future.

**Comment by praeclarum** [comment]
@5yunus2efendi  Async and await should work. You're seeing another bug #96 that I'm working on.

That said, be aware that browser apps are single threaded only. So while async and await work, they can do anything in a parallel. It's like using async and await on a single core machine.

@juanfranblanco HTTP client should work - not sure what Blazor is doing. That said, I haven't actually tried. :-) Let's track HttpClient in a separate issue if it doesn't work.

**Comment by 5yunus2efendi** [comment]
Ok, thanks, looking forward!

**Comment by hlogmans** [comment]
I'm running into a related problem that might shed some light on this issue:
I did use a task method (Navigation.PushAsync) without using async/await (forgot to add it). It does build, but I get a runtime error about type Task not found. When I added the async and await keywords, I got the above error. Seems there is missing some async/await magic below the surface. Maybe some Xamarin/MS folks can help you out, seen the potential impact this project has.

**Comment by praeclarum** [comment]
@hlogmans thanks for the details! Yeah that's a new perspective on the bug.

If you didn't reference it, then it makes sense that the linker would tear it out. But once you used it, it should have been included. I'm a bit confused.

Fortunately I can ask the big guns to help out if I can't figure it out.

**Comment by bitdisaster** [comment]
I saw the same with a simple Button click handler. Wanted to do a DisplayAlert and was wondering why it doesn't work. Without async it throws the System.TypeLoadException, with async it doesn't compile.

**Comment by praeclarum** [comment]
When I compile with the new logging, I get the error:

> Failed to resolve type System.Runtime.CompilerServices.TaskAwaiter

This seems to be a bug in mono wasm that I'm using.

**Comment by praeclarum** [comment]
I have filed a bug with mono since one of the facades seems to be missing some forwards. https://github.com/mono/mono/issues/8456
